version: "3"

services:

    db:
        image: postgres:12.0-alpine
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./backend/travel/.envs/.env.local

    web:
        build:
            context: ./backend/travel
            dockerfile: Dockerfile.prod
        container_name: web
        image: app
        command: gunicorn travel.wsgi:application --access-logfile - --workers=4 --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/src/app_code/staticfiles
            - media_volume:/home/src/app_code/mediafiles
        restart: on-failure

        ports:
            - 8000:8000

        env_file:
            - ./backend/travel/.envs/.env.local
        depends_on:
            - db

    frontend:
        build:
            context: ./front-end
            dockerfile: Dockerfile
        volumes:
            - build_folder:/frontend/build
            
    nginx:
        build:
          context: ./backend/travel/nginx
          dockerfile: Dockerfile.local
        volumes:
            - static_volume:/home/src/app_code/staticfiles
            - media_volume:/home/src/app_code/mediafiles
            - build_folder:/var/www/frontend
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume:
    media_volume:
    build_folder: