version: "3"

services:
    # db:
    #     image: mongo
    #     container_name: mongo
    #     volumes:
    #         - mongo_data:/data/db
    #     ports:
    #         - 27017:27017

    db:
        image: postgres:12.0-alpine
        container_name: db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.envs/.env.local

    web:
        build: .
        image: app
        command: python manage.py runserver 0.0.0.0:8000
        restart: on-failure
        volumes:
            - .:/app
        ports:
            - 8000:8000
        env_file:
            - ./.envs/.env.local
        stdin_open: true
        tty: true
        depends_on:
            - db

volumes:
    # mongo_data:
    postgres_data:
